BookShopInfrastructure/Controllers/OrderItemsController.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShopDomain.Model;
using BookShopInfrastructure;

namespace BookShopInfrastructure.Controllers
{
    public class OrderItemsController : Controller
    {
        private readonly BookShopContext _context;

        public OrderItemsController(BookShopContext context)
        {
            _context = context;
        }

        // GET: OrderItems
        public async Task<IActionResult> Index(int orderId)
        {
            var orderItems = _context.OrderItems
                .Include(o => o.Product)
                .Where(o => o.OrderId == orderId);

            ViewBag.OrderId = orderId;
            return View(await orderItems.ToListAsync());
        }

        // GET: OrderItems/Create
        public IActionResult Create(int orderId)
        {
            ViewData["OrderId"] = orderId;
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            return View(new OrderItem { OrderId = orderId }); 
        }

        // POST: OrderItems/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,Quantity,OrderId,Id")] OrderItem orderItem)
        {
            ModelState.Remove("Order");
            ModelState.Remove("Product");

            // Check if the OrderItem with the same ProductId already exists in the same Order
            bool exists = await _context.OrderItems
                .AnyAsync(o => o.OrderId == orderItem.OrderId && o.ProductId == orderItem.ProductId);

            if (exists)
            {
                ModelState.AddModelError("ProductId", "Товар вже доданий до цього замовлення.");
            }

            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new { orderId = orderItem.OrderId });
            }

            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", orderItem.ProductId);
            return View(orderItem);
        }


        // GET: OrderItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            var orderItem = await _context.OrderItems.FindAsync(id);
            if (orderItem == null)
                return NotFound();

            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", orderItem.ProductId);
            return View(orderItem);
        }

        // POST: OrderItems/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,Quantity,OrderId,Id")] OrderItem orderItem)
        {
            if (id != orderItem.Id)
                return NotFound();

            ModelState.Remove("Order");
            ModelState.Remove("Product");

            bool exists = await _context.OrderItems
                .AnyAsync(o => o.OrderId == orderItem.OrderId && o.ProductId == orderItem.ProductId && o.Id != orderItem.Id);

            if (exists)
            {
                ModelState.AddModelError("ProductId", "Товар вже доданий до цього замовлення.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), new { orderId = orderItem.OrderId });
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.OrderItems.Any(e => e.Id == orderItem.Id))
                        return NotFound();
                    else
                        throw;
                }
            }

            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name", orderItem.ProductId);
            return View(orderItem);
        }



        // GET: OrderItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItems
                                           .Include(o => o.Product)
                                           .FirstOrDefaultAsync(m => m.Id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);  
        }

        // POST: OrderItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var orderItem = await _context.OrderItems.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }

            _context.OrderItems.Remove(orderItem);
            await _context.SaveChangesAsync();

            TempData["SuccessMessage"] = "Товар успішно видалений з замовлення.";
            return RedirectToAction("Details", "Orders", new { id = orderItem.OrderId });
        }


        private bool OrderItemExists(int id)
        {
            return _context.OrderItems.Any(e => e.Id == id);
        }
    }
}

BookShopInfrastructure/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShopDomain.Model;
using BookShopInfrastructure;
using System.Linq;
using System.Threading.Tasks;
using BookShopInfrastructure.Services;

namespace BookShopInfrastructure.Controllers
{
    public class ProductsController : Controller
    {
        private readonly BookShopContext _context;
        private readonly ProductDataPortServiceFactory _productDataPostServiceFactory;

        public ProductsController(BookShopContext context, ProductDataPortServiceFactory productDataPostServiceFactory)
        {
            _context = context;
            _productDataPostServiceFactory = productDataPostServiceFactory;
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Id == id);
        }

        // GET: Products/Index
        public async Task<IActionResult> Index()
        {
            var products = await _context.Products
                                         .Include(p => p.Seller)
                                         .Include(p => p.BookStatus)
                                         .Include(p => p.Genres)
                                         .Include(p => p.Authors)
                                         .ToListAsync();
            return View(products);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Name");
            ViewData["BookStatusId"] = new SelectList(_context.BookStatuses, "Id", "Name");
            ViewData["Genres"] = new SelectList(_context.Genres, "Id", "Name");
            ViewData["Authors"] = new SelectList(_context.Authors, "Id", "Name");
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description,Year,Price,SellerId,BookStatusId")] Product product, int[] selectedGenres, int[] selectedAuthors)
        {
            var seller = await _context.Sellers.FindAsync(product.SellerId);
            var bookStatus = await _context.BookStatuses.FindAsync(product.BookStatusId);

            product.Seller = seller;
            product.BookStatus = bookStatus;

            ModelState.Clear();
            TryValidateModel(product); 

            var existingProduct = await _context.Products
                                                .Where(p => p.Name == product.Name && p.SellerId == product.SellerId && p.Year == product.Year)
                                                .FirstOrDefaultAsync();

            if (existingProduct != null)
            {
                ModelState.AddModelError(string.Empty, "Продукт з такою назвою, продавцем та роком видання вже існує.");
            }

            if (ModelState.IsValid)
            {
                _context.Add(product); 

                if (selectedGenres != null)
                {
                    foreach (var genreId in selectedGenres)
                    {
                        var genre = await _context.Genres.FindAsync(genreId);
                        if (genre != null)
                        {
                            product.Genres.Add(genre);
                        }
                    }
                }

                if (selectedAuthors != null)
                {
                    foreach (var authorId in selectedAuthors)
                    {
                        var author = await _context.Authors.FindAsync(authorId);
                        if (author != null)
                        {
                            product.Authors.Add(author);
                        }
                    }
                }

                await _context.SaveChangesAsync(); 
                return RedirectToAction(nameof(Index)); 
            }

            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Name", product.SellerId);
            ViewData["BookStatusId"] = new SelectList(_context.BookStatuses, "Id", "Name", product.BookStatusId);
            ViewData["Genres"] = new SelectList(_context.Genres, "Id", "Name", selectedGenres);
            ViewData["Authors"] = new SelectList(_context.Authors, "Id", "Name", selectedAuthors);

            return View(product);
        }




        // GET: Products/Edit/2
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                                        .Include(p => p.Seller)
                                        .Include(p => p.BookStatus)
                                        .Include(p => p.Genres)
                                        .Include(p => p.Authors)
                                        .FirstOrDefaultAsync(p => p.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Name", product.SellerId);
            ViewData["BookStatusId"] = new SelectList(_context.BookStatuses, "Id", "Name", product.BookStatusId);
            ViewData["Genres"] = new SelectList(_context.Genres, "Id", "Name", product.Genres.Select(g => g.Id));
            ViewData["Authors"] = new SelectList(_context.Authors, "Id", "Name", product.Authors.Select(a => a.Id));

            return View(product);
        }

        // POST: Products/Edit/2
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id, Name, Description, Year, Price, SellerId, BookStatusId")] Product product, int[] selectedGenres, int[] selectedAuthors)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            var seller = await _context.Sellers.FindAsync(product.SellerId);
            var bookStatus = await _context.BookStatuses.FindAsync(product.BookStatusId);

            product.Seller = seller;
            product.BookStatus = bookStatus;

            ModelState.Clear();
            TryValidateModel(product); 

            var existingProduct = await _context.Products
                                                .Where(p => p.Name == product.Name && p.SellerId == product.SellerId && p.Year == product.Year && p.Id != id)
                                                .FirstOrDefaultAsync();

            if (existingProduct != null)
            {
                ModelState.AddModelError(string.Empty, "Продукт з такою назвою, продавцем та роком видання вже існує.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product); 

                    product.Genres.Clear();
                    product.Authors.Clear();

                    if (selectedGenres != null)
                    {
                        foreach (var genreId in selectedGenres)
                        {
                            var genre = await _context.Genres.FindAsync(genreId);
                            if (genre != null)
                            {
                                product.Genres.Add(genre);
                            }
                        }
                    }

                    if (selectedAuthors != null)
                    {
                        foreach (var authorId in selectedAuthors)
                        {
                            var author = await _context.Authors.FindAsync(authorId);
                            if (author != null)
                            {
                                product.Authors.Add(author);
                            }
                        }
                    }

                    await _context.SaveChangesAsync(); 
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Index));
            }

            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Name", product.SellerId);
            ViewData["BookStatusId"] = new SelectList(_context.BookStatuses, "Id", "Name", product.BookStatusId);
            ViewData["Genres"] = new SelectList(_context.Genres, "Id", "Name", selectedGenres);
            ViewData["Authors"] = new SelectList(_context.Authors, "Id", "Name", selectedAuthors);

            return View(product);
        }


        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                                        .Include(p => p.Seller)
                                        .Include(p => p.BookStatus)
                                        .Include(p => p.Genres)
                                        .Include(p => p.Authors)
                                        .FirstOrDefaultAsync(p => p.Id == id);

            if (product == null)
            {
                return NotFound();
            }

            ViewData["Genres"] = new SelectList(_context.Genres, "Id", "Name");
            ViewData["Authors"] = new SelectList(_context.Authors, "Id", "Name");

            return View(product);
        }

        // POST: Products/AddGenreToProduct
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Route("Products/AddGenreToProduct")]
        public async Task<IActionResult> AddGenreToProduct(int id, int[] selectedGenres)
        {

BookShopInfrastructure/Views/OrderItems/Create.cshtml
@model BookShopDomain.Model.OrderItem

<h2>Додати товар до замовлення</h2>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Create" method="post">
    <input type="hidden" asp-for="OrderId" />

    <div class="form-group">
        <label asp-for="ProductId" class="control-label">Товар</label>
        <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
        <span asp-validation-for="ProductId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Quantity" class="control-label">Кількість</label>
        <input asp-for="Quantity" class="form-control" type="number" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-success">Зберегти</button>
    <a asp-controller="OrderItems" asp-action="Index" asp-route-orderId="@Model.OrderId" class="btn btn-secondary">Назад</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookShopInfrastructure/Views/OrderItems/Delete.cshtml
@model BookShopDomain.Model.OrderItem

<h2>Видалити товар з замовлення?</h2>

<div>
    <p><strong>Товар:</strong> @Model.Product.Name</p>
    <p><strong>Кількість:</strong> @Model.Quantity</p>
</div>

<form asp-action="Delete">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">🗑️ Видалити</button>
    <a asp-controller="OrderItems" asp-action="Index" asp-route-orderId="@Model.OrderId" class="btn btn-secondary">⬅️ Скасувати</a>
</form>

BookShopInfrastructure/Views/OrderItems/Details.cshtml
@model BookShopDomain.Model.OrderItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookShopInfrastructure/Views/OrderItems/Edit.cshtml
@model BookShopDomain.Model.OrderItem

<h2>Редагувати товар у замовленні</h2>

<div asp-validation-summary="All" class="text-danger"></div>


<form asp-action="Edit" asp-route-id="@Model.Id" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="OrderId" />

    <div class="form-group">
        <label asp-for="ProductId" class="control-label">Товар</label>
        <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
        <span asp-validation-for="ProductId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Quantity" class="control-label">Кількість</label>
        <input asp-for="Quantity" class="form-control" type="number" />
        <span asp-validation-for="Quantity" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Зберегти</button>
    <a asp-controller="OrderItems" asp-action="Index" asp-route-orderId="@Model.OrderId" class="btn btn-secondary"> Назад</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookShopInfrastructure/Views/OrderItems/Index.cshtml
@model IEnumerable<BookShopDomain.Model.OrderItem>

<h2>Товари у замовленні</h2>

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success">
        @TempData["SuccessMessage"]
    </div>
}

<table class="table">
    <thead>
        <tr>
            <th>Назва товару</th>
            <th>Кількість</th>
            <th>Дії</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Product.Name</td>
                <td>@item.Quantity</td>
                <td>
                    <a asp-controller="Products"
                       asp-action="Details"
                       asp-route-id="@item.ProductId"
                       asp-route-orderId="@ViewBag.OrderId"
                       class="btn btn-info">
                        Деталі товару
                    </a>
                    <a asp-controller="OrderItems" asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">
                        Редагувати
                    </a>
                    <form asp-action="Delete" asp-route-id="@item.Id" method="post" class="d-inline delete-form">
                        <button type="submit" class="btn btn-danger">
                            Видалити
                        </button>
                    </form>
                </td>
            </tr>
        }
    </tbody>
</table>

<a asp-controller="OrderItems" asp-action="Create" asp-route-orderId="@ViewBag.OrderId" class="btn btn-primary">
    Додати товар
</a>

<a asp-controller="Orders" asp-action="Index" class="btn btn-secondary">
    Назад до замовлень
</a>