BookShopInfrastructure/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookShopDomain.Model;
using BookShopInfrastructure;

namespace BookShopInfrastructure.Controllers
{
    public class StatusController : Controller
    {
        private readonly BookShopContext _context;

        public StatusController(BookShopContext context)
        {
            _context = context;
        }

        // GET: Status
        public async Task<IActionResult> Index()
        {
            var statuses = await _context.Statuses.ToListAsync();
            return View(statuses);
        }

        // GET: Status/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // GET: Status/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Status/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Id")] Status status)
        {
            var existingStatus = await _context.Statuses
                                                .FirstOrDefaultAsync(s => s.Name == status.Name);

            if (existingStatus != null)
            {
                ModelState.AddModelError(string.Empty, "Статус з таким ім'ям вже існує.");
            }

            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        // GET: Status/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }


        // POST: Status/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Name,Id")] Status status)
        {
            if (id != status.Id)
            {
                return NotFound();
            }

            var existingStatus = await _context.Statuses
                                                .Where(s => s.Name == status.Name && s.Id != id)
                                                .FirstOrDefaultAsync();

            if (existingStatus != null)
            {
                ModelState.AddModelError(string.Empty, "Статус з таким ім'ям вже існує.");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }


        // GET: Status/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var status = await _context.Statuses
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        // POST: Status/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var status = await _context.Statuses.FindAsync(id);
            if (status != null)
            {
                _context.Statuses.Remove(status);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(int id)
        {
            return _context.Statuses.Any(e => e.Id == id);
        }
    }
}

BookShopInfrastructure/Views/Status/Create.cshtml
@model BookShopDomain.Model.Status

<h2>Додати новий статус замовлення</h2>

<form asp-action="Create" method="post">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        <label asp-for="Name" class="control-label">Назва</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Зберегти</button>
    <a asp-controller="Status" asp-action="Index" class="btn btn-secondary">Скасувати</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookShopInfrastructure/Views/Status/Delete.cshtml
@model BookShopDomain.Model.Status

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Status</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookShopInfrastructure/Views/Status/Details.cshtml
@model BookShopDomain.Model.Status

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Status</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookShopInfrastructure/Views/Status/Edit.cshtml
@model BookShopDomain.Model.Status

<h2>Змінити статус замовлення</h2>

<form asp-action="Edit" method="post">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Name" class="control-label">Назва</label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Зберегти</button>
    <a asp-controller="Status" asp-action="Index" class="btn btn-secondary">Скасувати</a>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

BookShopInfrastructure/Views/Status/Index.cshtml
@model IEnumerable<BookShopDomain.Model.Status>

<h2>Статуси замовлень</h2>

<p>
    <a asp-controller="Status" asp-action="Create" class="btn btn-primary">Додати</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Назва</th>
            <th>Дії</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>
                    <a asp-controller="Status"
                       asp-action="Edit"
                       asp-route-id="@item.Id"
                       class="btn btn-warning">
                        Змінити
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>